image: curlimages/curl:latest

stages:
  - build

build:
  stage: build
  script:
    - "curl --silent -H \"Content-Type: application/json\" --data '{\"source_type\": \"Branch\", \"source_name\": \"development\"}' -X POST $DOCKER_HUB_BUILD_TRIGGER"
  only:
    - nightly
